sudo: false
language: node_js
node_js:
- '6'
- '4'
before_script:
  - npm install -g npm@4
branches:
  only:
    - master
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: never
