environment:
  matrix:
    - nodejs_version: '6'
    - nodejs_version: '4'

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install -g npm@3
  - node --version
  - npm --version

matrix:
  fast_finish: true

max_jobs: 6

platform: x64

version: '{build}'

shallow_clone: true

clone_depth: 1

build: off

before_test:
  - node --version
  - npm --version
  - npm install

test_script:
  - npm test

deploy: off

branches:
  only:
    - master
    - /^release\/*/
